#!/usr/bin/env python3
# Copyright 2017 kypo-network authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import json
import logging
import sys

from kyponet_master import setup


def main():
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument('--client-type')
    parser.add_argument('--config', '-c')
    args = parser.parse_args()

    if args.config:
        with open(args.config) as f:
            sandbox_config = json.load(f)
    else:
        sandbox_config = None
    output = setup.setup(args.client_type, sandbox_config)
    if args.client_type in setup.DRY_CLIENT_TYPES:
        json.dump(output, sys.stdout)


if __name__ == '__main__':
    main()
