#!/usr/bin/env python3
# Copyright 2017 kypo-network authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
import logging
import sys

from kyponet_client_legacy import configurator


def main():
    logging.basicConfig(level=logging.INFO)
    if sys.argv[1] == 'setup':
        config = json.load(sys.stdin)
        network_name = sys.argv[2]
        configurator.setup(config, network_name)
    elif sys.argv[1] == 'cleanup':
        configurator.cleanup()
    else:
        raise AttributeError()


if __name__ == '__main__':
    main()
